// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nmatch_cpp_tfreq
IntegerMatrix nmatch_cpp_tfreq(const CharacterVector& x, const CharacterVector& y, int nchar_min, const CharacterVector& token, const IntegerVector& token_freq);
RcppExport SEXP _nmatch_nmatch_cpp_tfreq(SEXP xSEXP, SEXP ySEXP, SEXP nchar_minSEXP, SEXP tokenSEXP, SEXP token_freqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nchar_min(nchar_minSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type token(tokenSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type token_freq(token_freqSEXP);
    rcpp_result_gen = Rcpp::wrap(nmatch_cpp_tfreq(x, y, nchar_min, token, token_freq));
    return rcpp_result_gen;
END_RCPP
}
// nmatch_cpp_tprob
DataFrame nmatch_cpp_tprob(const CharacterVector& x, const CharacterVector& y, int nchar_min, const CharacterVector& token_x, const IntegerVector& dist_x, const NumericVector& prob_x, const CharacterVector& token_y, const IntegerVector& dist_y, const NumericVector& prob_y, const CharacterVector& idf_token_x, const NumericVector& idf_x, double default_idf_x, const CharacterVector& idf_token_y, const NumericVector& idf_y, double default_idf_y, bool compute_idf_score);
RcppExport SEXP _nmatch_nmatch_cpp_tprob(SEXP xSEXP, SEXP ySEXP, SEXP nchar_minSEXP, SEXP token_xSEXP, SEXP dist_xSEXP, SEXP prob_xSEXP, SEXP token_ySEXP, SEXP dist_ySEXP, SEXP prob_ySEXP, SEXP idf_token_xSEXP, SEXP idf_xSEXP, SEXP default_idf_xSEXP, SEXP idf_token_ySEXP, SEXP idf_ySEXP, SEXP default_idf_ySEXP, SEXP compute_idf_scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type nchar_min(nchar_minSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type token_x(token_xSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type dist_x(dist_xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prob_x(prob_xSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type token_y(token_ySEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type dist_y(dist_ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prob_y(prob_ySEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type idf_token_x(idf_token_xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type idf_x(idf_xSEXP);
    Rcpp::traits::input_parameter< double >::type default_idf_x(default_idf_xSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type idf_token_y(idf_token_ySEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type idf_y(idf_ySEXP);
    Rcpp::traits::input_parameter< double >::type default_idf_y(default_idf_ySEXP);
    Rcpp::traits::input_parameter< bool >::type compute_idf_score(compute_idf_scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(nmatch_cpp_tprob(x, y, nchar_min, token_x, dist_x, prob_x, token_y, dist_y, prob_y, idf_token_x, idf_x, default_idf_x, idf_token_y, idf_y, default_idf_y, compute_idf_score));
    return rcpp_result_gen;
END_RCPP
}
// tokenize_name
std::vector<std::string> tokenize_name(const std::string& name, int nchar_min);
RcppExport SEXP _nmatch_tokenize_name(SEXP nameSEXP, SEXP nchar_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< int >::type nchar_min(nchar_minSEXP);
    rcpp_result_gen = Rcpp::wrap(tokenize_name(name, nchar_min));
    return rcpp_result_gen;
END_RCPP
}
// osa_distance
int osa_distance(const std::string& s1, const std::string& s2);
RcppExport SEXP _nmatch_osa_distance(SEXP s1SEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(osa_distance(s1, s2));
    return rcpp_result_gen;
END_RCPP
}
// token_idf_cpp
DataFrame token_idf_cpp(const CharacterVector& names, int nchar_min);
RcppExport SEXP _nmatch_token_idf_cpp(SEXP namesSEXP, SEXP nchar_minSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterVector& >::type names(namesSEXP);
    Rcpp::traits::input_parameter< int >::type nchar_min(nchar_minSEXP);
    rcpp_result_gen = Rcpp::wrap(token_idf_cpp(names, nchar_min));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nmatch_nmatch_cpp_tfreq", (DL_FUNC) &_nmatch_nmatch_cpp_tfreq, 5},
    {"_nmatch_nmatch_cpp_tprob", (DL_FUNC) &_nmatch_nmatch_cpp_tprob, 16},
    {"_nmatch_tokenize_name", (DL_FUNC) &_nmatch_tokenize_name, 2},
    {"_nmatch_osa_distance", (DL_FUNC) &_nmatch_osa_distance, 2},
    {"_nmatch_token_idf_cpp", (DL_FUNC) &_nmatch_token_idf_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nmatch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
