# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nmatch_cpp_tfreq <- function(x, y, nchar_min = 2L, token = character(), token_freq = integer()) {
    .Call(`_nmatch_nmatch_cpp_tfreq`, x, y, nchar_min, token, token_freq)
}

nmatch_cpp_similarity <- function(x, y, nchar_min = 2L, token_x = character(), idf_x = numeric(), default_idf_x = 1.0, token_y = character(), idf_y = numeric(), default_idf_y = 1.0) {
    .Call(`_nmatch_nmatch_cpp_similarity`, x, y, nchar_min, token_x, idf_x, default_idf_x, token_y, idf_y, default_idf_y)
}

nmatch_cpp_tprob <- function(x, y, nchar_min = 2L, token_x = character(), dist_x = integer(), prob_x = numeric(), token_y = character(), dist_y = integer(), prob_y = numeric()) {
    .Call(`_nmatch_nmatch_cpp_tprob`, x, y, nchar_min, token_x, dist_x, prob_x, token_y, dist_y, prob_y)
}

tokenize_name <- function(name, nchar_min = 2L) {
    .Call(`_nmatch_tokenize_name`, name, nchar_min)
}

osa_distance <- function(s1, s2) {
    .Call(`_nmatch_osa_distance`, s1, s2)
}

