# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tokenize_name <- function(name, nchar_min = 2L) {
    .Call(`_nmatch_tokenize_name`, name, nchar_min)
}

nmatch_cpp <- function(x, y, nchar_min = 2L) {
    .Call(`_nmatch_nmatch_cpp`, x, y, nchar_min)
}

